Repository realm/realm-swift, pull requests merged in 2019-11, with the labels that each got.

#6274 Add internal section with core/sync version information
  build.sh
Labels: T-Internal

#6282 Forward the url_prefix from auth responses to the sync session
  Realm/RLMJSONModels.h
  Realm/RLMJSONModels.m
  Realm/RLMSyncSessionRefreshHandle.mm
Labels: T-Internal

#6344 Update to sync 3.8.2
  CHANGELOG.md
  dependencies.list
Labels: T-Internal

#6343 Restore support for @objc enums on Swift objects
  .jenkins.yml
  CHANGELOG.md
  RealmSwift/Object.swift
  RealmSwift/Tests/MigrationTests.swift
  RealmSwift/Tests/ObjectAccessorTests.swift
  RealmSwift/Tests/ObjectCreationTests.swift
  RealmSwift/Tests/ObjectSchemaTests.swift
  RealmSwift/Tests/ObjectTests.swift
  RealmSwift/Tests/SwiftTestObjects.swift
  RealmSwift/Util.swift
  build.sh
  scripts/pr-ci-matrix.rb
Labels: T-Enhancement

#6352 Test the swiftpm build with asan and tsan on CI
  .jenkins.yml
  Realm/TestUtils/RLMMultiProcessTestCase.m
  build.sh
  scripts/pr-ci-matrix.rb
Labels: T-Internal

#6360 Replace Xcode 11.2 with 11.2.1
  .jenkins.yml
  CHANGELOG.md
  Jenkinsfile.releasability
  build.sh
  scripts/pr-ci-matrix.rb
Labels: T-Internal

#6359 Add Realm.fileExists() and Realm.deleteFiles()
  CHANGELOG.md
  Realm/RLMConstants.h
  Realm/RLMRealm.h
  Realm/RLMRealm.mm
  Realm/Tests/RealmTests.mm
  RealmSwift/Realm.swift
  RealmSwift/Tests/RealmTests.swift
Labels: T-Feature
