Repository realm/realm-swift, pull requests merged in 2019-05, with the labels that each got.

#6110 Update Sync.swift docs with deprecation warning.
  RealmSwift/Sync.swift
Labels: T:Doc

#6106 Use new async open functionality
  CHANGELOG.md
  Realm/RLMRealm.mm
Labels: T:Enhancement

#6160 Check the runtime type for a primary key in realm.create() rather than the static type
  CHANGELOG.md
  RealmSwift/Realm.swift
  RealmSwift/RealmCollection.swift
  RealmSwift/Tests/ObjectCreationTests.swift
Labels: T:Bug
