Repository realm/realm-swift, pull requests merged in 2019-09, with the labels that each got.

#6239 Clarify documentation for RLMRealmRefreshRequiredNotification
  Realm/RLMConstants.h
Labels: T-Doc

#6248 Update release packaging for Xcode 11
  .jenkins.yml
  .swiftlint.yml
  CHANGELOG.md
  Configuration/Base.xcconfig
  Configuration/Realm/Realm.xcconfig
  Jenkinsfile.releasability
  Realm/RLMPlatform.h.in
  RealmSwift/RealmCollection.swift
  RealmSwift/Tests/KVOTests.swift
  RealmSwift/Tests/ListTests.swift
  RealmSwift/Tests/MigrationTests.swift
  RealmSwift/Tests/ObjectTests.swift
  RealmSwift/Tests/PrimitiveListTests.swift
  build.sh
  dependencies.list
  examples/installation/build.sh
  examples/installation/ios/swift/CarthageExample/CarthageExample/AppDelegate.swift
  examples/installation/ios/swift/CarthageExample/CarthageExample/ViewController.swift
  examples/installation/ios/swift/CocoaPodsExample/CocoaPodsExample/AppDelegate.swift
  examples/installation/ios/swift/CocoaPodsExample/CocoaPodsExample/ViewController.swift
  examples/installation/ios/swift/DynamicExample/DynamicExample/AppDelegate.swift
  examples/installation/ios/swift/DynamicExample/DynamicExample/ViewController.swift
  examples/installation/osx/swift/CarthageExample/CarthageExample/AppDelegate.swift
  examples/installation/osx/swift/CarthageExample/CarthageExample/ViewController.swift
  examples/installation/osx/swift/DynamicExample/DynamicExample/AppDelegate.swift
  examples/installation/osx/swift/DynamicExample/DynamicExample/ViewController.swift
  examples/installation/watchos/swift/CarthageExample/CarthageExample.xcodeproj/project.pbxproj
  examples/ios/objc/RealmExamples.xcodeproj/project.pbxproj
  examples/ios/swift/Backlink/AppDelegate.swift
  examples/ios/swift/Encryption/AppDelegate.swift
  examples/ios/swift/Encryption/ViewController.swift
  examples/ios/swift/GroupedTableView/AppDelegate.swift
  examples/ios/swift/GroupedTableView/TableViewController.swift
  examples/ios/swift/Migration/AppDelegate.swift
  examples/ios/swift/Simple/AppDelegate.swift
  examples/ios/swift/TableView/AppDelegate.swift
  examples/ios/swift/TableView/TableViewController.swift
  examples/tvos/swift/DownloadCache/AppDelegate.swift
  examples/tvos/swift/DownloadCache/RepositoriesViewController.swift
  examples/tvos/swift/PreloadedData/AppDelegate.swift
  scripts/generate-rlmplatform.sh
  scripts/package_examples.rb
  scripts/pr-ci-matrix.rb
  scripts/reset-simulators.rb
Labels: T-Enhancement

#6252 Add support for suppressing notifications using closure-based write/transaction methods
  Realm/RLMRealm.h
  Realm/RLMRealm.mm
  Realm/Tests/NotificationTests.m
  RealmSwift/Realm.swift
  RealmSwift/Tests/RealmTests.swift
Labels: T-Enhancement

#6276 Upgrade to core 5.23.5
  CHANGELOG.md
  dependencies.list
Labels: T-Bug
