Repository realm/realm-swift, pull requests merged in 2024-06, with the labels that each got.

#8597 Upgrade to core 14.9.0
  .github/workflows/master-push.yml
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes, no-jira-ticket

#8614 Release 10.51.0
  CHANGELOG.md
  Package.swift
  Realm/Realm-Info.plist
  dependencies.list
Labels: no-changelog, no-jira-ticket

#8295 RCOCOA-2105 Fix crash when deleting a row from @ObservedSectionedResults
  CHANGELOG.md
  Realm/Tests/SwiftUITestHost/SwiftUITestHostApp.swift
  Realm/Tests/SwiftUITestHostUITests/SwiftUITestHostUITests.swift
  RealmSwift/SwiftUI.swift
  RealmSwift/Tests/SwiftUITests.swift
Labels: cla: yes

#8642 Upgrade to core v14.10.2
  CHANGELOG.md
  Package.swift
  Realm/Realm-Info.plist
  dependencies.list
Labels: cla: yes, no-jira-ticket

#8608 RCOCOA-2273: Add support for Logger categories/ Improve current logger.
  CHANGELOG.md
  Realm.xcodeproj/project.pbxproj
  Realm/ObjectServerTests/RLMSyncTestCase.mm
  Realm/RLMLogger.h
  Realm/RLMLogger.mm
  Realm/RLMLogger_Private.h
  Realm/RLMSyncManager.mm
  Realm/Tests/RealmTests.mm
  Realm/Tests/SwiftUISyncTestHost/ContentView.swift
  RealmSwift/Logger.swift
  RealmSwift/Realm.swift
  RealmSwift/Tests/RealmTests.swift
Labels: cla: yes
