Repository realm/realm-swift, pull requests merged in 2024-03, with the labels that each got.

#8484 RCOCOA-2238: Allow defining models with only computed properties
  CHANGELOG.md
  Realm/RLMObjectSchema.mm
  Realm/Tests/Swift/SwiftSchemaTests.swift
  RealmSwift/Tests/SwiftLinkTests.swift
  RealmSwift/Tests/SwiftTestObjects.swift
Labels: cla: yes

#8500 RPM-568: Add a workflow that verifies PR title
  .github/workflows/check-pr-title.yml
Labels: cla: yes, no-changelog

#8503 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/check-pr-title.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#8504 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/check-changelog.yml
  .github/workflows/issue-labeler.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#8502 Update packaging for Xcode 15.3
  .github/workflows/master-push.yml
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  Realm/Tests/SwiftUITestHost/SwiftUITestHostApp.swift
  RealmSwift/BSON.swift
  RealmSwift/Impl/RealmCollectionImpl.swift
  RealmSwift/Projection.swift
  RealmSwift/Query.swift
  RealmSwift/SwiftUI.swift
  build.sh
  ci_scripts/ci_post_clone.sh
  contrib/UpgradingXcode.md
  scripts/create-release-package.rb
  scripts/package_examples.rb
  scripts/pr-ci-matrix.rb
  scripts/xcode_cloud_helper.rb
Labels: cla: yes, no-jira-ticket

#8490 Introduce `_customRealmProperties()` to all Realm Objects to allow for client-generated RLMProperties (via Swift Macros)
  Realm.xcodeproj/project.pbxproj
  RealmSwift/Impl/SchemaDiscovery.swift
  RealmSwift/Tests/ObjectCustomPropertiesTests.swift
Labels: cla: yes

#8505 Only commit the changelog in the add empty changelog release step
  .github/workflows/publish-release.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#8520 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/lock-threads.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#8511 Add NSPrivacyAccessedAPICategoryDiskSpace to the privacy manifest
  CHANGELOG.md
  Realm/PrivacyInfo.xcprivacy
Labels: cla: yes, no-jira-ticket

#8517 RCOCOA-2308: Add GHA workflow for core prebuilds
  .github/workflows/build-binaries.yml
  build.sh
  dependencies.list
  scripts/download-core.sh
Labels: cla: yes, no-changelog

#8496 Upgrade to core 14
  CHANGELOG.md
  Package.swift
  Realm/ObjectServerTests/RLMSyncTestCase.mm
  Realm/RLMBSON_Private.hpp
  Realm/RLMLogger.mm
  Realm/RLMMongoCollection.mm
  Realm/RLMObservation.mm
  Realm/RLMQueryUtil.mm
  Realm/RLMSyncConfiguration.mm
  Realm/RLMSyncManager.mm
  Realm/RLMUtil.mm
  Realm/TestUtils/TestUtils.mm
  Realm/Tests/PerformanceTests.m
  Realm/Tests/QueryTests.m
  RealmSwift/Tests/ObjectCustomPropertiesTests.swift
  RealmSwift/Tests/PerformanceTests.swift
  RealmSwift/Tests/SectionedResultsTests.swift
  dependencies.list
Labels: cla: yes, no-jira-ticket

#8526 Upgrade to core 14.4.1
  CHANGELOG.md
  Package.swift
  Realm/RLMSyncSession.mm
  Realm/Realm-Info.plist
  dependencies.list
Labels: cla: yes

#8525 Add core version to build-binaries workflow
  .github/workflows/build-binaries.yml
Labels: cla: yes, no-changelog, no-jira-ticket
