Repository realm/realm-swift, pull requests merged in 2024-05, with the labels that each got.

#8563 RCOCOA-2344 Drop support for Xcode 14
  .github/workflows/build-binaries.yml
  .github/workflows/master-push.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  Configuration/Base.xcconfig
  Configuration/Realm/Realm.xcconfig
  Package.swift
  Realm.podspec
  Realm/ObjectServerTests/RealmServer.swift
  Realm/ObjectServerTests/SwiftAsymmetricSyncServerTests.swift
  Realm/ObjectServerTests/SwiftMongoClientTests.swift
  Realm/ObjectServerTests/SwiftSyncTestCase.swift
  RealmSwift.podspec
  RealmSwift/Aliases.swift
  RealmSwift/EmbeddedObject.swift
  RealmSwift/Impl/RealmCollectionImpl.swift
  RealmSwift/Map.swift
  RealmSwift/Object.swift
  RealmSwift/Projection.swift
  RealmSwift/Realm.swift
  RealmSwift/RealmCollection.swift
  RealmSwift/Results.swift
  RealmSwift/SectionedResults.swift
  RealmSwift/Tests/MapTests.swift
  RealmSwift/Tests/ObjectTests.swift
  RealmSwift/Tests/ProjectionTests.swift
  RealmSwift/Tests/RealmCollectionTypeTests.swift
  RealmSwift/Tests/RealmTests.swift
  RealmSwift/Tests/TestUtils.swift
  RealmSwift/Util.swift
  build.sh
  scripts/package_examples.rb
  scripts/pr-ci-matrix.rb
Labels: cla: yes

#8560 RCOCOA-2289: Update Base url API
  CHANGELOG.md
  Realm/ObjectServerTests/AsyncSyncTests.swift
  Realm/ObjectServerTests/RLMObjectServerTests.mm
  Realm/ObjectServerTests/SwiftObjectServerTests.swift
  Realm/RLMApp.mm
  Realm/RLMApp_Private.h
  RealmSwift/App.swift
  dependencies.list
Labels: cla: yes

#8492 RCOCOA-2285: Wire up the new progress notifications
  CHANGELOG.md
  Realm/ObjectServerTests/RealmServer.swift
  Realm/ObjectServerTests/SwiftFlexibleSyncServerTests.swift
  Realm/ObjectServerTests/SwiftObjectServerTests.swift
  Realm/ObjectServerTests/config_overrides.json
  Realm/RLMAsyncTask.h
  Realm/RLMAsyncTask.mm
  Realm/RLMSyncSession.h
  Realm/RLMSyncSession.mm
  RealmSwift/Realm.swift
  RealmSwift/Sync.swift
  contrib/Development.md
  dependencies.list
Labels: cla: yes

#8564 Bump Core to 14.6.2
  CHANGELOG.md
  Package.swift
  Realm/TestUtils/TestUtils.mm
  build.sh
  dependencies.list
Labels: cla: yes, no-jira-ticket

#8569 Prepare fot 10.50.0
  .github/workflows/master-push.yml
  CHANGELOG.md
  Package.swift
  Realm/Realm-Info.plist
  dependencies.list
Labels: cla: yes

#8572 Fix using initialSubscriptions with @AsyncOpen and @AutoOpen
  CHANGELOG.md
  Realm/ObjectServerTests/SwiftServerObjects.swift
  Realm/ObjectServerTests/SwiftSyncTestCase.swift
  Realm/ObjectServerTests/SwiftUIServerTests.swift
  RealmSwift/SwiftUI.swift
Labels: cla: yes, no-jira-ticket

#8579 Fix documentation links
  Realm.podspec
  Realm/RLMObject.h
  Realm/RLMProperty.mm
  Realm/RLMResults.h
  RealmSwift.podspec
  RealmSwift/Aliases.swift
  SUPPORT.md
  docs/README.md
  examples/README.md
Labels: cla: yes, no-changelog, no-jira-ticket

#8598 RCOCOA-2365 Update release packaging for Xcode 15.4
  .github/workflows/master-push.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  Realm/ObjectServerTests/AsyncSyncTests.swift
  Realm/ObjectServerTests/RealmServer.swift
  Realm/ObjectServerTests/SwiftObjectServerTests.swift
  Realm/ObjectServerTests/SwiftServerObjects.swift
  Realm/RLMObjectId.mm
  Realm/TestUtils/TestUtils.mm
  Realm/TestUtils/include/TestUtils.h
  Realm/Tests/Swift/SwiftObjectInterfaceTests.swift
  Realm/Tests/Swift/SwiftPropertyTypeTest.swift
  RealmSwift/AsymmetricObject.swift
  RealmSwift/EmbeddedObject.swift
  RealmSwift/List.swift
  RealmSwift/Map.swift
  RealmSwift/MutableSet.swift
  RealmSwift/Object.swift
  RealmSwift/ObjectId.swift
  RealmSwift/Tests/CodableTests.swift
  RealmSwift/Tests/KeyPathTests.swift
  RealmSwift/Tests/MigrationTests.swift
  RealmSwift/Tests/ModernObjectCreationTests.swift
  RealmSwift/Tests/ObjectCreationTests.swift
  RealmSwift/Tests/ObjectTests.swift
  RealmSwift/Tests/ProjectionTests.swift
  RealmSwift/Tests/QueryTests.swift
  RealmSwift/Tests/RealmTests.swift
  RealmSwift/Tests/SwiftTestObjects.swift
  RealmSwift/Tests/TestUtils.swift
  RealmSwift/Tests/TestValueFactory.swift
  build.sh
  examples/tvos/swift/DownloadCache/RepositoriesViewController.swift
  scripts/package_examples.rb
  scripts/pr-ci-matrix.rb
Labels: cla: yes

#8573 Fix -[RLMApp baseURL] always being nil
  CHANGELOG.md
  Realm/ObjectServerTests/AsyncSyncTests.swift
  Realm/ObjectServerTests/RLMObjectServerTests.mm
  Realm/ObjectServerTests/RealmServer.swift
  Realm/ObjectServerTests/SwiftFlexibleSyncServerTests.swift
  Realm/ObjectServerTests/SwiftObjectServerTests.swift
  Realm/ObjectServerTests/SwiftUIServerTests.swift
  Realm/ObjectServerTests/setup_baas.rb
  Realm/RLMApp.mm
  Realm/RLMUser.mm
  Realm/Tests/SwiftUITestHostUITests/SwiftUITestHostUITests.swift
  RealmSwift/App.swift
  RealmSwift/Sync.swift
  ci_scripts/ci_post_clone.sh
  dependencies.list
Labels: cla: yes, no-jira-ticket

#8599 Release 10.50.1
  CHANGELOG.md
  Package.swift
  Realm/Realm-Info.plist
  dependencies.list
Labels: cla: yes, no-jira-ticket
